### ISSUE TITLE
Olá, Felipe Castros Sales!

### ISSUE THREAD

**Issue by Felipe-Souza-Pereira-Lima** [felipecastrosales/Course-Github#7]
Olá, sou o Felipe fundador da Dsa Software Fundation uma organização sem fins lucrativos que cria softwares avançados, em Python, Html, Css, Javascript e junto de @caue-alves, @eduardohor fazemos projetos de código-aberto e seu core é em Python3, e sei que você pode colaborar muito em futuros projetos e sistemas, isso é um convite para minha organização [Dsa Software](https://github.com/Dsa-Software) e [Dsa Terminal](https://github.com/Dsa-Terminal)! E ai aceita?

**Comment by felipecastrosales** [comment]
Opa, boa tarde, tudo em?
Como funciona? Só tenho intimidade com HTML-CSS, acho que poderia ajudar de
alguma forma!

Em sex., 9 de out. de 2020 às 14:25, Felipe Souza Pereira Lima <
notifications@github.com> escreveu:

**Comment by Felipe-Souza-Pereira-Lima** [comment]
O Dsa terminal é uma emulador de Linux para Windows ele pode instalar pacotes e além de ter uma boa didática ele pode ser redistribuído e é fácil de usar ele tem comandos complexos mas que parece muito com Linux Ubuntue tem node.js e Lua embutido no sistema

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Ele funciona como o Bash do linux

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Estou bem

**Comment by felipecastrosales** [comment]
Que projeto massa Felipe! Vi no email e a ideia é muito legal!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
> Que projeto massa Felipe! Vi no email e a ideia é muito legal!

Obrigado

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Aceita participar?

**Comment by felipecastrosales** [comment]
Sim!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Vou enviar o convite

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Você tem que ver a sua caixa de entrada do email

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Afinal qual seu email

**Comment by felipecastrosales** [comment]
opa, te respondi lá no gmail! soufeliposales@gmail.com

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Obrigado

**Comment by Felipe-Souza-Pereira-Lima** [comment]
> opa, te respondi lá no gmail! soufeliposales@gmail.com

Não fui eu você tem que acesar o link

**Comment by Felipe-Souza-Pereira-Lima** [comment]
O github que mandou

**Comment by felipecastrosales** [comment]
Show!
